# docker-compose.yml
services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    env_file:
      - .env
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ${VAR_LOG_PATH}:${VAR_LOG_PATH}
      - ${STATS_BACK_LOGS_PATH}:${STATS_BACK_LOGS_PATH}
      # - /var/log:/var/log
      # - /home/linroot/code/statsboard/statsboards-backend/src/logs:/home/linroot/code/statsboard/statsboards-backend/src/logs
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    # command: /bin/sh -c 'envsubst < /etc/promtail/config.yml > /etc/promtail/config_substituted.yml && promtail -config.file=/etc/promtail/config_substituted.yml'
    networks:
      - loki
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - loki

networks:
  loki:

volumes:
  loki-data:
  grafana-data:
