# promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
  # - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # - job_name: journal
  #   journal:
  #     max_age: 12h
  #     labels:
  #       job: systemd-journal
  #   relabel_configs:
  #     - source_labels: ['__journal__systemd_unit']
  #       target_label: 'unit'
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: ${VAR_LOG_PATH}
          # __path__: /var/log/*.log
  - job_name: statsboards
    static_configs:
      - targets:
          - localhost
        labels:
          job: statsboards
          app: backend
          __path__: ${STATS_BACK_LOGS_PATH_BACK}
          # __path__: /home/linroot/code/statsboard/statsboards-backend/src/logs/backend.log
  - job_name: nginx-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: access
          __path__: ${NGINX_ACCESS_LOG_PATH}
  - job_name: nginx-error
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx
          app: error
          __path__: ${NGINX_ERROR_LOG_PATH}
    # pipeline_stages:
    #   - regex:
    #       expression: '^(?P<ts>[^ ]+ [^ ]+) - (?P<logger>[^ ]+) - (?P<level>[^ ]+) - (?P<message>.*)'
    #   - timestamp:
    #       source: ts
    #       format: "2006-01-02 15:04:05,000" # Go format for your timestamp
    #       location: Europe/Moscow # Set to your timezone
    #   - labels:
    #       logger:
    #       level:
