# promtail-config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: ${LOKI_URL}
  # - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__hostname']
        target_label: 'host'
      - source_labels: ['__journal__unit']
        target_label: 'unit'
      - source_labels: ['__journal__priority']
        target_label: 'priority'
#  - job_name: system
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*
  # Scrape logs from Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      # Filter only the nginx and backend containers by name
      - source_labels: [ '__meta_docker_container_name' ]
        regex: 'backend|nginx|frontend'
        action: keep
      # Label the logs with container name
      - source_labels: [ '__meta_docker_container_name' ]
        target_label: 'container'
      # Label the logs with Docker image
      - source_labels: [ '__meta_docker_image' ]
        target_label: 'image'
      # Add labels for Compose service and project
      - source_labels: [ '__meta_docker_label_com_docker_compose_service' ]
        target_label: 'service'
      - source_labels: [ '__meta_docker_label_com_docker_compose_project' ]
        target_label: 'project'
      - source_labels: [ '__line__' ]
        regex: '.*(WARNING|ERROR|CRITICAL).*'
        action: keep
#  - job_name: statsboards
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: statsboards
#          app: backend
#          __path__: ${STATS_BACK_LOGS_PATH_BACK}
#  - job_name: nginx-access
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: nginx
#          app: access
#          __path__: ${NGINX_ACCESS_LOG_PATH}
#  - job_name: nginx-error
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: nginx
#          app: error
#          __path__: ${NGINX_ERROR_LOG_PATH}
